### ISSUE TITLE
Is .txt data package a meaningful example

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/example-data-packages#21]
The [text-file](https://github.com/frictionlessdata/example-data-packages/tree/master/text-file) data package packages a simple text file. While this appears correct, I'm wondering about the value of this example and if it should be retained?

**Comment by anuveyatsu** [comment]
@Stephen-Gates in my view, `.txt` files should be considered as any other non-tabular files so that this data package is meaningful not as a "text-file" but as a "non-tabular" data package.

**Comment by Stephen-Gates** [comment]
Thanks @anuveyatsu I've updated the example and PR #36 is ready. Would you like to review?
