### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish. could translate the license and any other document that has text

### ISSUE THREAD

**Issue by LuigiBaute** [frictionlessdata/example-data-packages#22]
> Use the Issue Title above to provide a summary of the problem, data request or other issue.
> Fill out the relevant sections below. Delete sections as appropriate.
> Provide as much detail as you can to help us help you.

### Desired Data  
> Use this section for new data requests. If you're reporting a problem, delete this section.

### Current Behaviour (for problems)
> When reporting a problem, describe what happens that isn't expected behaviour?

### Expected Behaviour
> When reporting a problem, describe what should happen

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1.
2.
3.

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix things quicker.

*
*

**Comment by Stephen-Gates** [comment]
Wow! Hi @LuigiBaute thank you very much for your offer 😃 

You are very welcome to start by translating the repository [README.md](https://github.com/frictionlessdata/example-data-packages/blob/master/README.md) to Spanish.

@rufuspollock @pwalsh and crew, do you have recommendations for file naming of translations? I didn't see anything in the [coding standards](https://github.com/okfn/coding-standards). 

It would be really interesting to provide an example data package using the [language support](https://frictionlessdata.io/specs/patterns/#language-support) pattern.

**Comment by Stephen-Gates** [comment]
I've just added https://github.com/frictionlessdata/example-data-packages/pull/24 that adds a data package ready to accept Spanish language values in properties like `"es": " "`.  The English equivalent is above this value and looks like `"": "ISO 639-1 Language Codes"`

@LuigiBaute are you comfortable making a pull request for `iso-639-1-language-codes/datapackage.json` once #24 is merged? 

Alternatively I can provide a list of terms for you to translate - whatever is easiest for you.

**Comment by Stephen-Gates** [comment]
Added translations to #24 using google translate.
