### ISSUE TITLE
What license should be applied to example data packages?

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/example-data-packages#3]
assuming the data and data package is original and not licensed elsewhere what licence should be applied? 

CC0?

**Comment by roll** [comment]
cc @rufuspollock

**Comment by rufuspollock** [comment]
@Stephen-Gates you can use the license **you** choose. Open Data Commons Public Domain Dedication and License, CC0, Open Data Commons Attribution etc.

**Comment by Stephen-Gates** [comment]
Applied CC0
