### ISSUE TITLE
open-data-day-tweets-2018 data package is invalid

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/example-data-packages#40]
open-data-day-tweets-2018 data package is invalid:

- `author` is wrong - see https://github.com/frictionlessdata/example-data-packages/blob/master/resources/contributors.json for examples and the [`contributors`](https://frictionlessdata.io/specs/data-package/#contributors) spec
- [`licenses`](https://frictionlessdata.io/specs/data-package/#licenses)  is wrong - see https://github.com/frictionlessdata/example-data-packages/blob/master/resources/licenses.json and the soon to be published https://github.com/frictionlessdata/website/pull/160  
- the license given does not have a url. When I googled the term used, it does not appear to provide a license.  ~~licenses used should be open licenses.~~
- `goodtables.yml` not updated

**Comment by pwalsh** [comment]
> licenses used should be open licenses.

Everything in above comment is fine, but data packages do not need to be openly licensed.

**Comment by Stephen-Gates** [comment]
closed by #47
