### ISSUE TITLE
Update readme for finance-vix data package

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/example-data-packages#42]
The [finance-vix](https://github.com/frictionlessdata/example-data-packages/tree/master/finance-vix) data package is used in [tutorials](https://frictionlessdata.io/docs/)

Update the [README.md](https://github.com/frictionlessdata/example-data-packages/blob/master/finance-vix/README.md) to present a better example and mention that the data package is used in tutorials

**Comment by Stephen-Gates** [comment]
I don't believe we should publish this data given the [copyright notice](http://www.cboe.com/common/terms-and-conditions-for-use-of-cboe-websites). 

I believe the licence applied and the statement on https://datahub.io/core/finance-vix#license is incorrect. 

Seeking advice @rufuspollock

**Comment by rufuspollock** [comment]
@Stephen-Gates can you clarify what about that copyright notice (which i understand covers the content of that site not data). Plus this is the US and this is a simple collection of factual data so I think this is PD 😄

**Comment by Stephen-Gates** [comment]
@rufuspollock you may be right but I read section 2 differently. Emphasis mine

> 2. Copyrights, Trademarks, Service Marks, And Proprietary Rights.
> 
> The design of, as well as the materials, content, text, graphics, and **information contained in, the Website ("Materials") are owned, licensed, or controlled by Cboe** or the party credited as the owner, licensor, or provider of such Materials. **The Materials on the Website, including, but not limited to all menu pages, content, text, video, audio and graphics are protected by copyrights, trademarks, service marks, and/or other proprietary rights and laws of the United States and other countries**. The Website is also protected as a collective work or compilation under United States copyright and other laws. You agree to comply with all applicable copyright and other laws. You agree to comply with any guidelines for linking to the Website that may be posted on the Website. **You may view, print and download one copy of the contents for your personal noncommercial use in connection with products and services offered by Cboe, provided, you maintain all copyright, trademark and other notices contained on the Materials. You may not otherwise copy, reproduce, alter, store either in hard copy or in an electronic retrieval system, license, transmit, display, broadcast, create a derivative work (for example, a financial product, service or index) from, publish, rent, sublicense, distribute, or otherwise use in whole or in part in any other manner the Materials without Cboe's prior written consent except to the extent that such use constitutes "fair use" under the "Copyright Act of 1976",** as amended from time to time. Request for such consent must be made in writing and should be mailed to Cboe Options Exchange, Attention: Internet Marketing, 400 S. LaSalle Street, Chicago, IL 60605; or you may send an e-mail via the "Contact Cboe" form located at http://www.cboe.com/Contact. Any Materials contained in the Website that are owned by, or about, you shall not be subject to the limitations on use contained in these Terms.

The data is not credited to another party, so I can only assume it is copyright Cboe.

Cboe are a US company, not government, so I believe copyright applies.

The data may be facts but perhaps the work is in how the data was selected and organised.

Rufus would you please edit the README.md as I don't believe I have the knowledge to address licensing correctly.

**Comment by rufuspollock** [comment]
@Stephen-Gates this talks about content not data ("menu pages, content, text, video, audio and graphics"). This a boilerplate website terms and conditions.

Also the point i made about copyright is not about federal public domain dedication but about the Feist decision 😄 - see http://opendefinition.org/guide/data/ for more.

**Comment by Stephen-Gates** [comment]
Thanks @rufuspollock 

https://github.com/frictionlessdata/example-data-packages/pull/46
