### ISSUE TITLE
Public domain mark on resources/licenses.json is missing "name"

### ISSUE THREAD

**Issue by vitorbaptista** [frictionlessdata/example-data-packages#48]
According to the spec, the license must have a `name`, but public domain mark doesn't. See https://github.com/frictionlessdata/example-data-packages/blob/2b78581d8087ee638b98aa8a3562e34348a80d12/resources/licenses.json#L36-L39

**Comment by Stephen-Gates** [comment]
I believe the example is correct but this is an excellent test for my guide on  [Applying licenses, waivers or public domain marks](https://discuss.okfn.org/t/applying-licenses-waivers-or-public-domain-marks/6440) which is a PR on https://github.com/frictionlessdata/website/pull/160 (feedback welcome)

[`licenses`](https://frictionlessdata.io/specs/data-package/#licenses) only has a `name` if it's an [open licence assessed to be comfomant  with the open definition](http://licenses.opendefinition.org/licenses/groups/od.json). The [public domain mark](https://creativecommons.org/share-your-work/public-domain/pdm/) isn't a licence or a waiver, it's just a mark to indicate that the data has no copyright. It has no entry in the open definition and hence can't have a `name`.


> `licenses` MUST be an array. Each item in the array is a License. Each MUST be an `object`. The object MUST contain a `name` property **and/or** a `path` property. It MAY contain a `title` property.

source: https://frictionlessdata.io/specs/data-package/#licenses (emphasis mine)

> ## What is the Public Domain Mark?
> 
> The Public Domain Mark (“PDM”) is a tool that allows anyone to mark and tag a work that is free of known copyright restrictions worldwide, all in a way that clearly communicates that status to the public and allows it to be easily discoverable. The PDM is not a legal instrument like CC0 or our licenses; there is no accompanying legal code or agreement. It should only be used to label a work that is already free of known copyright restrictions around the world, typically very old works. It should not be used to attempt to change a work’s current status under copyright law, or affect any person’s rights in a work. Just like CC0 and our licenses, PDM has a metadata-supported deed and is machine readable, allowing works properly tagged to be readily discovered over the Internet.

source: https://wiki.creativecommons.org/wiki/PDM_FAQ#What_is_the_Public_Domain_Mark.3F

**Comment by vitorbaptista** [comment]
Oh, I missed the "and/or a `path` property". Thanks for the clarification :+1:
