### ISSUE TITLE
review https://github.com/datapackage-examples for more example data packages

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/example-data-packages#49]
As [suggested](https://github.com/frictionlessdata/implementations/issues/28#issuecomment-375025271) by @rufuspollock, review https://github.com/datapackage-examples for data packages to include in this repository.

**Comment by rufuspollock** [comment]
@Stephen-Gates less to copy across and merge - more to be aware.

If we do want to merge (which could be a good idea) we should chat a bit more about optimal way to do that (for DataHub we need to push the datapackage-examples to datahub.io/examples regularly ...)

**Comment by Stephen-Gates** [comment]
Added reference in readme
